name: "codeql-extractor-iac"
description: "CodeQL Extractor for Infrastructure as Code"

inputs:
  token:
    description: GitHub Token
    default: ${{ github.token }}

  source-root:
    description: "Path of the root source code directory, relative to $GITHUB_WORKSPACE."
    default: "./"

  extractor-version:
    description: "Pin to a version of the IaC Extractor to use (release tag)."

  sarif:
    description: "SARIF File Output"
    default: "codeql-iac.sarif"

runs:
  using: "node16"
  main: ".github/action/dist/index.js"
