name: Build and Compile Extractor Pack

on:
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly

      - name: "Build Extractor"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh extensions install github/gh-codeql
          gh codeql set-version latest

          ./scripts/create-extractor-pack.sh

      - name: "Run Tests"
        run: |
          ./scripts/run-tests.sh
