name: Build and Compile Extractor Pack

on:
  pull_request:
    branches: ["main", "develop"]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Build Extractor"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./scripts/create-extractor-pack.sh
