name: Build and Publish Extractor Pack

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Build Extractor"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./scripts/create-extractor-pack.sh

      - name: "Publish Extractor Pack"
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./scripts/publish-extractor-pack.sh
